name = "cf-aiproxy"
main = "src/index.js"
compatibility_date = "2025-01-24"

routes = [
  { pattern = "proxy.draftresume.app", custom_domain = true },
  { pattern = "proxy.draftpatent.app", custom_domain = true }
]

[vars]
AI_ACCOUNT_HASH = "a5ac50eac3fc3bba71323b08817bd04e"
AI_GATEWAY_NAME = "drafting-gateway"
ALLOWED_ORIGINS = "http://localhost:3000,http://localhost:8000,https://draftresume.app,https://draftpatent.app"

[observability.logs]
enabled = true